### ISSUE TITLE
Unas preguntas para entender que es lo que quieres hacer

### ISSUE THREAD

**Issue by abr4xas** [rimorsoft/Rimback#1]
Hola, interesante el proyecto y pues, voy con algunas preguntas para poder entender lo que tienes y poder colaborar.

- Para qué tienes nuevamente el modelo `User` si ya por defecto lo trae laravel.
- De qué trata la tabla `post_term`?  Entiendo que es una pivot pero aun no logro ver lo que quieres hacer.
- Sobre los comentarios, no crees que sea algo innecesario de hacer existiendo servicios como disqus que con simplemente agregar un pequeño script ya está listo esta parte de los comentarios sin la necesidad de obligar al usuario a registrarse en el sitio web para dejar un comentario. 

Saludos.

**Comment by italomoralesf** [comment]
Hola amigo, muchas gracias por revisar el material...

1. Aún estoy en la etapa de planificación, al tener la base hecha haré un video donde explique cada cosa.
2. post_term guardará las relaciones entre etiquetas, categorías y posts. 
3. Sobre los comentarios estoy pensando dar la opción de incluir facebook o disqu

Cuando le dé mas forma haré un video explicativo.
